#!/usr/bin/env bash
set -o errexit   # exit on error
set -o pipefail  # exit on error in pipes
set -o nounset   # exit on unset variable
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
cd "$ROOT_DIR"


# generate
exec scripts/cmake/generate -D BUILD_SHARED_LIBS=ON "$@"
